# Generated by Django 3.2 on 2022-06-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=30)),
                ('trainer_about', models.CharField(blank=True, max_length=254, null=True)),
                ('program1', models.CharField(blank=True, max_length=254, null=True)),
                ('program2', models.CharField(max_length=254)),
                ('program3', models.CharField(blank=True, max_length=254, null=True)),
                ('trainer_highlight', models.TextField(blank=True, max_length=254, null=True)),
                ('trainer_text', models.TextField()),
                ('trainer_text_hidden', models.TextField()),
                ('trainer_goals', models.CharField(blank=True, max_length=254, null=True)),
                ('trainer_image_url', models.URLField(max_length=1024)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
