# Generated by Django 3.2 on 2022-06-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_trainers_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='trainer_goals',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_highlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='trainer_text_hidden',
            field=models.TextField(blank=True, null=True),
        ),
    ]
